# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('value', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DWS',
            fields=[
                ('value', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dns', models.ManyToManyField(to='ubcdataapp.DNS')),
                ('dws', models.ManyToManyField(to='ubcdataapp.DWS')),
                ('license', models.ManyToManyField(to='ubcdataapp.License')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('value', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='so',
            field=models.ManyToManyField(to='ubcdataapp.SO'),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubcdataapp.Version'),
        ),
    ]
